config/routes.rb
Fixnixgrc::Application.routes.draw do
  resources :policies

  get "dashboard/index"
  devise_for :users

  root 'dashboard#index'

  

end

app/models/policy.rb
class Policy < ActiveRecord::Base
	# attr_accessible :attach 
	# has_attached_file :attach
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def _chart
  end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :set_policy, only: [:show, :edit, :update, :destroy]

  # GET /policies
  # GET /policies.json
  def index
    @policies = Policy.all
  end

  # GET /policies/1
  # GET /policies/1.json
  def show
    @policy = Policy.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = PoliciesPdf.new(@policy)
        send_data pdf.render, filename: "policy_#{@policy.p_name}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  # GET /policies/new
  def new
    @policy = Policy.new
  end

  # GET /policies/1/edit
  def edit
  end

  # POST /policies
  # POST /policies.json
  def create
    @policy = Policy.new(policy_params)

    respond_to do |format|
      if @policy.save
        format.html { redirect_to @policy, notice: 'Policy was successfully created.' }
        format.json { render action: 'show', status: :created, location: @policy }
      else
        format.html { render action: 'new' }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /policies/1
  # PATCH/PUT /policies/1.json
  def update
    respond_to do |format|
      if @policy.update(policy_params)
        format.html { redirect_to @policy, notice: 'Policy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policies/1
  # DELETE /policies/1.json
  def destroy
    @policy.destroy
    respond_to do |format|
      format.html { redirect_to policies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_policy
      @policy = Policy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def policy_params
      params.require(:policy).permit(:p_name, :p_ref, :c_name, :c_ref, :scope, :objectives)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/views/dashboard/index.html.erb
<%= render partial: "layouts/header"%>
<div class="container">
<div class="span9 offset well">
<%= javascript_include_tag "/javascript/highcharts.js", "chartkick" %>
<script type="text/javascript" src="/javascript/themes/skies.js"></script>
<%= pie_chart Policy.group("p_name").count %>
</div>
</div>

app/views/layouts/_header.html.erb
<br><br>
<div class="container">
		<div class="header">
		</div>
		<div class="navbar navbar-inverse">
			<div class="navbar-inner">
				<div class="nav-collapse collapse">
					<ul class="nav">
						<li><a href="/">Dashboard</a></li>
						<li><a href="/">Library</a></li>
						<li><a href="policies">Policy</a></li>
						<li><a href="controls">Control Standards</a></li>
						<li><a href="businessunits">Business Units</a></li>
						<li><a href="groups">Groups</a></li>
						<li><a href="reports">Reports</a></li>
						<li><a href="exception">Exceptions</a></li>
						<li><a href="archieve">Archive</a></li>
						<li class="dropdown"><a href="admin" class="dropdown-toggle" data-toggle="dropdown">Admin <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="admin/user">Users</a></li>
								<li><a href="admin/setting">Settings</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
</div>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>FixNix GRC</title>
    <link rel="icon" type="image/png" href="/images/favicon.ico">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "highcharts" %>
   
    
    <style type="text/css">
    body{
        background-color:#D9B68B;
    }
    </style>
</head>
<body>  
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?  
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> 
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %> 
   <% end %>
   
</div>
    <%= yield %>
</body>
</html>

app/views/policies/_form.html.erb
<%= render partial: "layouts/header"%>
<html>
<%= form_for(@policy) do |f| %>
  <% if @policy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@policy.errors.count, "error") %> prohibited this policy from being saved:</h2>
      <ul>
      <% @policy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
<div class="span9 offset well">
  <center><h2>New Policy</h2></center> 
  <div class="field">
    <%= f.label :policy_name %><br>
    <%= f.text_field :p_name %>
  </div>
  <div class="field">
    <%= f.label :policy_reference %><br>
    <%= f.text_field :p_ref %>
  </div>
  <div class="field">
    <%= f.label :control_name %><br>
    <%= f.text_field :c_name %>
  </div>
  <div class="field">
    <%= f.label :control_reference %><br>
    <%= f.text_field :c_ref %>
  </div>
  <div class="field">
    <%= f.label :policy_scope %><br>
    <%= f.text_area :scope %>
  </div>
  <div class="field">
    <%= f.label :policy_objectives %><br>
    <%= f.text_area :objectives %>
  </div>
  <div>
     <b> attachment </b><br/>
     <%= f.file_field :attach %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
</div>
<% end %>

app/views/policies/edit.html.erb
<h1>Editing policy</h1>

<%= render 'form' %>

<%= link_to 'Show', @policy %> |
<%= link_to 'Back', policies_path %>

app/views/policies/index.html.erb
<%= render partial: "layouts/header"%> 
<center>
<h4><i>Existing policies</i></h4>
<br><br>
<table border="2">
  <thead>
    <tr>
      <th>Policy name</th>
      <th>Policy reference</th>
      <th>Control name</th>
      <th>Control reference</th>      
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @policies.each do |policy| %>
      <tr>
        <td><%= policy.p_name %></td>
        <td><%= policy.p_ref %></td>
        <td><%= policy.c_name %></td>
        <td><%= policy.c_ref %></td>        
        <td><%= link_to 'Show', policy %>&nbsp;&nbsp;
        <%= link_to 'Edit', edit_policy_path(policy) %>&nbsp;&nbsp;
        <%= link_to 'Destroy', policy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<a class="btn btn-success" href="policies/new">New Policy</a>
</center>
</div>

app/views/policies/new.html.erb
<%= render 'form' %>
<center>
<%= link_to 'Back', policies_path, :class=> "btn btn-info" %>
</center>

app/views/policies/show.html.erb
<%= render partial: "layouts/header"%> 
<center>
<div class="container">
<div class="span9 offset well">
<p id="notice"><%= notice %></p>

<table border="0">
  <tr><td><strong>Policy name:</strong></td>
  <td><%= @policy.p_name %></td></tr>
<tr><td>&nbsp;&nbsp;</td></tr>

<tr><td><strong>Poilct reference:</strong></td>
  <td><%= @policy.p_ref %></td></tr>
  <tr><td>&nbsp;&nbsp;</td></tr>

<tr><td><strong>Control name:</strong></td>
  <td><%= @policy.c_name %></td></tr>
  <tr><td>&nbsp;&nbsp;</td></tr>

  <tr><td><strong>Control reference:</strong></td>
  <td><%= @policy.c_ref %></td></tr>
  <tr><td>&nbsp;&nbsp;</td></tr>

  <tr><td><strong>Scope:</strong></td>
  <td><%= @policy.scope %></td></tr>
  <tr><td>&nbsp;&nbsp;</td></tr>

  <tr><td><strong>Objectives:</strong></td>
  <td><%= @policy.objectives %></td></tr>
  <tr><td>&nbsp;&nbsp;</td></tr>
  </table>
  <p>
  <b> File attached </b></a>
  <br/>
</p>

<p>
<%= link_to 'Edit', edit_policy_path(@policy), :class=>"btn btn-info" %>&nbsp;&nbsp;
<%= link_to "Report", policy_path(@policy, format: "pdf"), :class=>"btn btn-info"%>&nbsp;&nbsp;
<%= link_to 'Back', policies_path, :class=>"btn btn-info" %>
</p>
</div>
</div></center>